org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX est obligatoire pour Compose.
android.useAndroidX=true

# Le .aar produit par gomobile n'embarque que les ABI demandées au bind.
# On ne cible que arm64-v8a pour contenir la taille de l'APK ; ajouter
# armeabi-v7a ici et au bind pour couvrir les vieux
# appareils 32 bits.
android.defaults.buildfeatures.buildconfig=false
android.nonTransitiveRClass=true
android.nonFinalResIds=true

kotlin.code.style=official
